### ISSUE TITLE
picker问题

### ISSUE THREAD

**Issue by liuzengze** [react-visual-design/react-visual-design#1]
对于picker,datePicker的弹出层，能不能限定在表示手机的那个div框里

**Comment by kokiy** [comment]
没有明白你的问题 可以截个图啥的 更清楚吗

**Comment by liuzengze** [comment]
![image](https://user-images.githubusercontent.com/42337043/101735024-2f05a200-3afc-11eb-92f5-03dfce7b862e.png)
就像这样，弹出层会从页面底部弹出，不会从代表手机的div框里面弹出

**Comment by kokiy** [comment]
好的 我处理一下

**Comment by kokiy** [comment]
好的 我处理一下 目前没有是配过picker

**Comment by kokiy** [comment]
已经修复 解决方案是用iframe & postmessage 通信

**Comment by kokiy** [comment]
![image](https://user-images.githubusercontent.com/15773714/102018412-0bff1a80-3da8-11eb-96a0-276aaaf2a2d9.png)
